### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by satvikpendem** [novuhq/novu-rust#41]
I see that the package isn't on `cargo` and the instructions to `cargo install novu` are crossed out on the README, so how do I actually use this package? Is it still in development and just not ready yet?

**Comment by c12i** [comment]
Although the crate is not available on [crates.io](crates.io), it's still possible to use it via `git`. Simply add this to your `Cargo.toml`:

```toml
[dependencies]
novu = { version = "0.1.0", git = "https://github.com/novuhq/novu-rust.git" }
```

This should probably be documented in the `README`

cc @unicodeveloper
